# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tagli < Formula
  desc ""
  homepage ""
  version "0.1.1"

  on_macos do
    on_intel do
      url "https://github.com/taxintt/tagli/releases/download/v0.1.1/tagli_Darwin_x86_64.tar.gz"
      sha256 "3153a0c583b8a5a85675f12b9c229474f2288e0345b8d7f2676c53620275588f"

      def install
        bin.install "tagli"
      end
    end
    on_arm do
      url "https://github.com/taxintt/tagli/releases/download/v0.1.1/tagli_Darwin_arm64.tar.gz"
      sha256 "f478c6662c467d4c332df3ddcf4029f53bc4787a65991dc063ef71bd52af197e"

      def install
        bin.install "tagli"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/taxintt/tagli/releases/download/v0.1.1/tagli_Linux_x86_64.tar.gz"
        sha256 "a3b97ded68af53b620cef46f383333df76364f4068cee5c01b7cc1e478e2893b"

        def install
          bin.install "tagli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/taxintt/tagli/releases/download/v0.1.1/tagli_Linux_arm64.tar.gz"
        sha256 "5988989f09967ddb1a738067d4d22fdb586e99e9e68c1eab6403e3698ebb90ac"

        def install
          bin.install "tagli"
        end
      end
    end
  end
end
